import { Metadata } from "next";
import { Header } from "@/components/header";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Terms of Service - 30tools | Usage Guidelines and Policies",
  description: "Read our terms of service to understand the guidelines and policies for using 30tools AI platform. Fair use and responsible AI tool usage.",
  keywords: ["terms of service", "usage guidelines", "30tools terms", "AI tools policy"],
  alternates: {
    canonical: "https://ai-tools.30tools.com/terms",
  },
};

export default function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      <Header />
      
      <main className="container mx-auto px-4 py-16">
        <div className="max-w-4xl mx-auto">
          <h1 className="text-4xl font-bold mb-8">Terms of Service</h1>
          <p className="text-muted-foreground mb-8">Last updated: January 1, 2025</p>

          <div className="prose prose-gray dark:prose-invert max-w-none space-y-8">
            <section>
              <h2 className="text-2xl font-semibold mb-4">1. Acceptance of Terms</h2>
              <p>
                By accessing and using 30tools (&ldquo;the Service&rdquo;), you accept and agree to be bound by 
                the terms and provision of this agreement. If you do not agree to abide by the above, 
                please do not use this service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">2. Description of Service</h2>
              <p>
                30tools provides free AI-powered tools for writing, creativity, productivity, and more. 
                Our services include but are not limited to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Text generation and editing tools</li>
                <li>Content creation assistants</li>
                <li>Writing enhancement utilities</li>
                <li>Creative ideation tools</li>
                <li>Developer assistance tools</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">3. Acceptable Use</h2>
              <p>You agree to use our services only for lawful purposes and in accordance with these Terms. You agree not to:</p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Generate harmful, offensive, or illegal content</li>
                <li>Attempt to reverse engineer or abuse our AI systems</li>
                <li>Use the service for spam or automated content generation at scale</li>
                <li>Violate any applicable laws or regulations</li>
                <li>Infringe upon intellectual property rights of others</li>
                <li>Attempt to overwhelm our servers with excessive requests</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">4. Content and Intellectual Property</h2>
              <p>
                You retain ownership of any content you input into our tools. However, you grant us 
                a limited license to process your content through our AI systems for the purpose of 
                providing the service.
              </p>
              <p>
                The output generated by our AI tools is provided as-is. While you may use the generated 
                content, we recommend reviewing and editing it before publication, as AI-generated content 
                may contain inaccuracies or require refinement.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">5. Service Availability</h2>
              <p>
                We strive to maintain high availability of our services, but we do not guarantee 
                uninterrupted access. We reserve the right to:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Modify or discontinue services with or without notice</li>
                <li>Implement usage limitations to ensure fair access</li>
                <li>Perform maintenance that may temporarily affect availability</li>
                <li>Update our AI models and capabilities</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">6. Disclaimers</h2>
              <p>
                Our services are provided &ldquo;as is&rdquo; without warranties of any kind. We do not guarantee:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>The accuracy or completeness of AI-generated content</li>
                <li>That the service will meet your specific requirements</li>
                <li>That the service will be error-free or uninterrupted</li>
                <li>That defects will be corrected</li>
              </ul>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">7. Limitation of Liability</h2>
              <p>
                In no event shall 30tools be liable for any indirect, incidental, special, consequential, 
                or punitive damages, including without limitation, loss of profits, data, use, goodwill, 
                or other intangible losses, resulting from your use of the service.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">8. Third-Party Services</h2>
              <p>
                Our service relies on third-party AI providers (such as OpenAI) and other services. 
                Your use of our platform may be subject to the terms and policies of these third-party 
                providers as well.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">9. Termination</h2>
              <p>
                We may terminate or suspend access to our service immediately, without prior notice 
                or liability, for any reason whatsoever, including without limitation if you breach 
                the Terms.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">10. Changes to Terms</h2>
              <p>
                We reserve the right, at our sole discretion, to modify or replace these Terms at any time. 
                If a revision is material, we will try to provide at least 30 days notice prior to any 
                new terms taking effect.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">11. Governing Law</h2>
              <p>
                These Terms shall be interpreted and governed by the laws of the jurisdiction in which 
                our company is incorporated, without regard to its conflict of law provisions.
              </p>
            </section>

            <section>
              <h2 className="text-2xl font-semibold mb-4">12. Contact Information</h2>
              <p>
                If you have any questions about these Terms of Service, please contact us at:
              </p>
              <ul className="list-disc pl-6 space-y-2">
                <li>Email: legal@30tools.com</li>
                <li>Website: https://ai-tools.30tools.com/contact</li>
              </ul>
            </section>
          </div>
        </div>
      </main>

      <Footer />
    </div>
  );
}